# Site settings
title: "Mes ressources"
description: "Une collection de fiches de lecture et de ressources pédagogiques"
url: "https://ouaisfieu.github.io"   # Remplacez par votre nom d'utilisateur GitHub
baseurl: ""              # Laissez vide pour un site à la racine

# --- Thème ----------------------------------------------------------
#
# Par défaut, on utilise Minimal Mistakes comme remote_theme.
# Pour tester un autre thème, décommentez la ligne correspondante
# et commentez les autres.

remote_theme: "mmistakes/minimal-mistakes@4.26.1"   # Minimal Mistakes
# remote_theme: "just-the-docs/just-the-docs"         # Just the Docs
# remote_theme: "mmistakes/so-simple-theme"           # So Simple

# Choisissez un jeu de couleurs (skins) Minimal Mistakes :
# default, air, aqua, contrast, dark, dirt, neon, plum, mint
minimal_mistakes_skin: "dark"

# --- Plugins GitHub Pages compatibles -------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# --- Collections ----------------------------------------------------
collections:
  resources:
    output: true
    permalink: /resources/:path/

# --- Options diverses ----------------------------------------------
search: true
markdown: kramdown
