title: "ouaisfi.eu"
description: "La citoyenneté, c'est le brol"
url: "https://ouaisfieu.github.io"  
baseurl: "/dossiers"                 
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint" # change ici pour dark, plum, default, air, aqua, contrast, dirt, neon, mint
theme_skin_toggle: true

# --- Plugins (compatibles GitHub Pages) -------------------------------
plugins:
#  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate         # pour la pagination

# --- Collections ------------------------------------------------------
# collections:
#  dossiers:
#    output: true
#    permalink: /dossiers/:title/

# --- Search (Lunr.js) -------------------------------------------------
search:
  provider: lunr
  lunr_lang: fr
  output: search.json

# --- Markdown ----------------------------------------------------------
markdown: kramdown

# --- Pagination --------------------------------------------------------
paginate: 10
paginate_path: "/page:num/"

# --- Valeurs par défaut (hero, dark mode) -----------------------------
defaults:
  # Hero banner sur la page d’accueil (index.md avec layout: home ou default)
  - scope:
      path: ""
      type: "pages"
    values:
      header:
        title: "ouaisfi.eu"
        subtitle: "La citoyenneté, c'est le brol"

  # Active le switch dark/light global
  - scope:
      path: ""
    values:
