# _config.yml

###############################################################
# Palette : clair ↔ sombre
###############################################################
palette:
  # Thème clair (chargé par défaut)
  - scheme: default            # reprend le skin défini plus bas
    toggle:
      icon: fas fa-sun         # l’icône Font Awesome pour “soleil”
      label: Mode clair

  # Thème sombre
  - scheme: dark
    toggle:
      icon: fas fa-moon        # icône “lune”
      label: Mode sombre


# --- Métadonnées du site -----------------------------------------------
title: "Mes dossiers choisis"
description: "Quatre analyses pour comprendre notre monde"

# --- URLs --------------------------------------------------------------
url: "https://ouaisfieu.github.io"  
baseurl: "/dossiers"                 

# --- Thème -------------------------------------------------------------
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
theme: null          
minimal_mistakes_skin: "aqua"

# --- Plugins (compatibles GitHub Pages) -------------------------------
plugins:
#  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate         # pour la pagination

# --- Collections ------------------------------------------------------
# collections:
#  dossiers:
#    output: true
#    permalink: /dossiers/:title/

# --- Search (Lunr.js) -------------------------------------------------
search:
  provider: lunr
  lunr_lang: fr
  output: search.json

# --- Markdown ----------------------------------------------------------
markdown: kramdown

# --- Pagination --------------------------------------------------------
paginate: 10
paginate_path: "/page:num/"

# --- Valeurs par défaut (hero, dark mode) -----------------------------
defaults:
  # Hero banner sur la page d’accueil (index.md avec layout: home ou default)
  - scope:
      path: ""
      type: "pages"
    values:
      header:
        title: "Mes dossiers choisis"
        subtitle: "Quatre analyses pour comprendre notre monde"

  # Active le switch dark/light global
  - scope:
      path: ""
    values:
