title: "Mes ressources"
description: "Une collection de fiches de lecture et de ressources pédagogiques"

# --- URLs --------------------------------------------------------------
url: "https://ouaisfieu.github.io"   # racine de tes pages GitHub
baseurl: "/dossiers"                 # nom exact de ton dépôt (avec /)

# --- Thème -------------------------------------------------------------
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
theme: null          # évite le conflit avec le thème par défaut GitHub
minimal_mistakes_skin: "aqua"   # change ici pour dark, plum, default, air, aqua, contrast, dirt, neon, mint

# --- Plugins (compatibles GitHub Pages) -------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# --- Collections ------------------------------------------------------
collections:
  resources:
    output: true
    permalink: /resources/:path/

search: true
markdown: kramdown
